services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  backend:
    build: ./back-end
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back-end:/code
    environment:
      - SECRET_KEY=${SECRET_KEY:?err}
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    ports:
      - "8000:8000"
    depends_on:
      - migration
      - db
  migration:
    build: ./back-end
    command: bash -c "python manage.py makemigrations && python manage.py migrate"
    volumes:
      - ./back-end:/code
    depends_on:
      - db