# Generated by Django 4.0.6 on 2022-07-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_moves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgamelog',
            name='timeDifferenceCurrent',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
