# Generated by Django 4.0.6 on 2022-07-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('save_moves', '0002_chessgamelog_timedifferencecurrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chessgamelog',
            name='moves',
        ),
        migrations.RemoveField(
            model_name='chessgamelog',
            name='timeTracker',
        ),
    ]
