# Generated by Django 4.0.6 on 2022-07-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_moves', '0003_remove_chessgamelog_moves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgamelog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
