# Generated by Django 4.0.6 on 2022-07-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_moves', '0004_alter_chessgamelog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessgamelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
