# Generated by Django 4.0.6 on 2022-07-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('save_moves', '0005_alter_chessgamelog_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chessgamelog',
            options={'ordering': ('token',)},
        ),
        migrations.AddField(
            model_name='chessgamelog',
            name='token',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='chessgamelog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
